#-------------------------------
# Site Settings
title: "My-Super.App: Self-Custodial Bitcoin Retairement"
logo: # You can add own logo. For example '/images/logo.png'.
author: Pawel
description: "Self-Custodial Bitcoin Retairement."


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    


#-------------------------------
# Hero Settings
hero:
  hero__title: "My-Super.App"
  hero__description: "Unlock a future of financial independence with My-Super.App, Australia’s leading self-custodial Bitcoin SMSF platform. <br/> <br/> 
  Take full control of your retirement, with direct access to your Bitcoin wallet, complex signing schemas for unmatched security, and the ability to maximize your investments through superannuation benefits. <br/> <br/> 
  Whether you’re planning for unforeseen circumstances or aiming to grow your savings tax-efficiently, My-Super.App ensures your journey into Bitcoin retirement is secure, compliant, and tailored for long-term success."
#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Our Projects
  portfolio__gallery:
    - image: /webpage_initial/images/gallery-01.jpg
      title: Samantha Gades
      description: Brown photo frame beside wall <a href="https://unsplash.com/photos/8Od75hgzb9Y">Unsplash</a>

    - image: /webpage_initial/images/gallery-02.jpg
      title: Paula Vermeulen
      description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

    - image: /webpage_initial/images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /webpage_initial/images/gallery-04.jpg
      title: Nord Wood
      description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    - image: /webpage_initial/images/gallery-05.jpg
      title: Luca Bravo
      description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    - image: /webpage_initial/images/gallery-06.jpg
      title: Isaac Benhesed
      description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    - image: /webpage_initial/images/gallery-07.jpg
      title: Water Journal
      description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    - image: /webpage_initial/images/gallery-08.jpg
      title: Luca Bravo
      description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    - image: /webpage_initial/images/gallery-09.jpg
      title: Books and Laptop
      description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: I am interested! # Add your Title
  mailchimp__identifier: github.us12.list-manage.com/subscribe/post?u=2d4bec70a28350ded35452795&id=468938da57&amp;f_id=00bd4ce0f0
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#ffbe2e" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).



#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
#- {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
#- {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
#- {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
#- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
#- {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: hello@my-super.app # Add your email for contact form
  description: Contact our team to join the conversation on trust and verification in the world of Bitcoin. Your feedback and engagement are essential as we work together to create a trustworthy Bitcoin community. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: mysuperapp # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
